server:
  port: 8090

  
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Customermanagementservice
          uri: lb://Customermanagementservice
          predicates:
            - Path=/customers/**
        - id: orderingservice
          uri: lb://orderingservice
          predicates:
            - Path=/**
        - id: restaurantsearchservice
          uri: lb://restaurantsearchservice
          predicates:
            - Path=/**, /restaurants/**

applicationconfigutation:
  host: http://localhost
  port: 3305
  username: payment-dev-updated-final
  password: payment-dev-updated-final
