    
server:
  port: 8081

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/orderdb
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   
restaurant:
  search:
    item:
      url: http://localhost:8080/item/id/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
user: user
password: password 
